[build-system]
requires = ["git-versiointi>=1.7c4", "setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "django-mummola"
description = "Mummolan varauskalenteri"
readme = "README.md"
authors = [
  {name = "Antti Hautaniemi", email = "antti.hautaniemi@me.com"},
]
requires-python = ">= 3.13"
dynamic = ["version"]
dependencies = [
  "django-protoni>=0.5.5",
  "django-sivumedia",
  "django-yhdiste",
  "gunicorn",
  "psycopg[binary]",
  "whitenoise",
]

[project.entry-points."django.osoitteisto"]
mummola = "mummola.nakyma"

[project.entry-points."django.sovellus"]
mummola = "mummola"

[project.entry-points."django.asetukset"]
mummola = "mummola.asetukset"

[tool.setuptools.packages.find]
include = ["mummola*"]
