# Generated by Django 6.1.1 on 2026-09-20 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Varaus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alku', models.DateTimeField(verbose_name='alku')),
                ('loppu', models.DateTimeField(verbose_name='loppu')),
                ('tarkeys', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='tärkeys')),
                ('kuvaus', models.TextField(blank=True, verbose_name='kuvaus')),
                ('lapset', models.PositiveSmallIntegerField(default=0, verbose_name='lasten määrä')),
                ('sijainti', models.CharField(choices=[('mummola', 'Mummolassa'), ('muualla', 'muualla')], max_length=16, verbose_name='sijainti')),
                ('tekija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mummolan_varaukset', to=settings.AUTH_USER_MODEL, verbose_name='tekijä')),
            ],
            options={
                'verbose_name': 'varaus',
                'verbose_name_plural': 'varaukset',
                'ordering': ['alku'],
            },
        ),
    ]
