# Generated by Django 6.1.1 on 2026-09-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mummola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='varaus',
            name='aikuiset',
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name='aikuisten määrä',
            ),
        ),
        migrations.AddField(
            model_name='varaus',
            name='koirat',
            field=models.PositiveSmallIntegerField(
                default=0,
                verbose_name='koirien määrä',
            ),
        ),
    ]
